name: 00-Testing Required Workflows

run-name: "Auto-fail - via ${{ github.event_name }}"

on:
  workflow_dispatch:
  push:

jobs:
  auto-fail:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
